apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: garm-provider-k8s
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
