# SPDX-License-Identifier: MIT

apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: RoleBinding
metadata:
  name: garm-provider-k8s
  namespace: runner
subjects:
  - kind: ServiceAccount
    namespace: garm-server
    name: garm-server
roleRef:
  kind: ClusterRole
  name: garm-provider-k8s
  apiGroup: rbac.authorization.k8s.io
